---

- hosts: all
  become: true
  tasks:

  - name: update index
    apt:
      update_cache: yes

  - name: dinstalle apache2 package
    apt:
      name: apache2
      state: absent


  - name: php-support-remove 
    apt:
      name: libapache2-mod-php
      state: absent
