---

- hosts: all
  become: true
  tasks:

  - name: update index
    apt:
      update_cache: yes

  - name: installe apache2 package
    apt:
      name: apache2
      state: latest


  - name: php-support
    apt: 
      name: libapache2-mod-php
      state: latest
